# -*- coding: utf-8 -*-
"""Atividade aula 10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFXrkOWvBDZNBhQGMmH0zkt2lDlbLm3K
"""

#DESAFIO

# DESENVOLVEDOR DE BACK-END, E PRECISA DESENVOLVER AS
# ESTRUTURAS BÁSICAS DO FUNCIONAMENTO DE UM E-COMMERCE
# CRIAR UM SISTEMA DE E-COMMERCE
# PRECISA TER UM FORMULÁRIO
# O USUÁRIO PRECISA VER QUAIS PRODUTOS EXISTEM
# ESCOLHER O PRODUTO
# ESCOLHER A FORMA DE PAGAMENTO
# MENSAGEM DE DESPEDIDA

# CONSTANTES
# NOME DO USÁRIO
# ID CODIGO
# CPF DO USUÁRIO

nome = input('Digite seu Nome: ')
cpf = input('Digite o sue CPF: ')
email = input('Digite seu e-mail: ')
print(f'''Seus dados são:
Nome: {nome}
CPF: {cpf}
E-mail: {email}
''')
print(f'Olá bem vindo {nome} ao nosso e-commerce!')
print('Confira os produtos abaixo!')

def compra():

    lista_produtos = ['1 - Tenis  R$250,00', '2 - Camisa  R$80,00', '3 - Calça  R$120,00']

    for lista_produtos in  lista_produtos:
        print(lista_produtos)

    tenis = 250
    camisa = 80
    calca = 120
    escolha = int(input('Digite o número do produto escolhido: '))
    if escolha == 1:
        print(f'Certo o valor total é R${tenis},00')
    elif escolha == 2:
        print(f'Certo o valor total é R${camisa},00')
    elif escolha == 3:
        print(f'Certo o valor total é R${calca},00')
    else:
      compra()

    print('Informe o endereço de entrega:')
    entrega = input('>> ')

    print('''
    Escolha a forma de pagamento:
    1 - Cartão de crédito
    2 - Cartão de débito
    ''')

    pagamento = int(input('Digite a forma de pagamento: '))

    if pagamento == 1:
        input('Digite o nome do titular do cartão: ')
        input('Digite o número do cartão: ')
        input('Digite a data de validade do cartão: ')
        input('Digite o código CVC do cartão: ')
    elif pagamento == 2:
        input('Digite o nome do titular do cartão: ')
        input('Digite o número do cartão: ')
        input('Digite a data de validade do cartão: ')
        input('Digite o código CVC do cartão: ')
    else:
        print('Forma de pagamento não encontrada!')
        print('Tente novamente!')
        compra()


    print(f'''
    Compra realizada com sucesso, seu pedido chegara em breve em {entrega}!
    ''')
    print('Obrigado pela preferência volte sempre!')

while True:
    compra()