# -*- coding: utf-8 -*-
"""aula 12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NRwJFyx4i0HwjMK63wzzsOIESwBRyq0I
"""

import statistics

lista = [1,3,6,9]
s = 0
for b in lista:
    tamanho = len(lista)
    s = s + b
print(s/tamanho)

import statistics

lista = [1, 2, 3, 4, 5]
media = statistics.mean(lista)
print("Média:", media)

import statistics

lista = [1, 2, 3, 4, 5]
mediana = statistics.median(lista)
print("Mediana:", mediana)

import statistics

lista = [1, 2, 2, 3, 3, 3, 4, 4, 5]
moda = statistics.mode(lista)
print("Moda:", moda)

import statistics

lista = [1, 2, 3, 4, 5]
desvio_padrao = statistics.stdev(lista)
print("Desvio Padrão:", desvio_padrao)

import statistics

lista = [1, 2, 3, 4, 5]
variancia = statistics.variance(lista)
print("Variância:", variancia)

import statistics

def calcular_media(lista):
    # Verifica se a lista está vazia
    if not lista:
        return "A lista está vazia, não é possível calcular a média."

    # Calcula a média utilizando a função mean da biblioteca statistics
    media = statistics.mean(lista)
    return f"A média dos números na lista é: {media}"

# Exemplo de uso
numeros = [10, 20, 30, 40, 50, 60, 70]
print(calcular_media(numeros))

# VOCÊ É UM DEV E PRECISA CRIAR UM SISTEMA PARA UMA ESCOLA.
# SISTEMA DE NOTAS DE ALUNOS QUE MOSTRE COM ESTATISTICA A MODA E A MEDIA, VARIANÇA E DESVIO DE PADRÃO, DAS NOTAS DE ALUNOS DE UM COLÉGIO, ALÉM DE MOSTRAR MENOR E A  MAIOR NOTA, SEPARE EM FUNÇÕES DIFERENTES


import statistics

def calc(lista = []):
    nota1 = input('Digite sua nota: ')
    nota2 = input('Digite sua nota: ')
    nota3 = input('Digite sua nota: ')
    nota4 = input('Digite sua nota: ')
    lista.append(nota1)
    lista.append(nota2)
    lista.append(nota3)
    lista.append(nota4)

def estatisticas():
    moda = statistics.mode(lista)
    print("Moda:", moda)

    media = statistics.mean(lista)
    print('Média:', media)

    varianca = statistics.variance(lista)
    print('Variança:', varianca)

    desvio_padrao = statistics.stdev(lista)
    print("Desvio de padrão", desvio_padrao)


calc(lista)
estatisticas()

# Você é um analista de dados, e decidiu trocar de emprego.
# Utilize a media, moda, mediana e o desvio padrão para decidir qual empresa faz sentido para você:
# Justificar por que decidiu por essa empresa.
# Verifique isso através dos salários:

import statistics

def empresa1():
    empresa1 = [1000,6000,1200,8000,10000]

    moda = statistics.mode(empresa1)
    print("Moda:", moda)

    media = statistics.mean(empresa1)
    print('Média:', media)

    varianca = statistics.variance(empresa1)
    print('Variança:', varianca)

    desvio_padrao = statistics.stdev(empresa1)
    print("Desvio de padrão:", desvio_padrao)

empresa1()

print('---------------------------------------------')

def empresa2():
    empresa2 = [5000,4000,3000,2000,7000]

    moda = statistics.mode(empresa2)
    print('Moda:', moda)

    media = statistics.mean(empresa2)
    print('Média:', media)

    varianca = statistics.variance(empresa2)
    print("Variança:", varianca)

    desvio_padrao = statistics.stdev(empresa2)
    print("Desvio de padrão:", desvio_padrao)

empresa2()

print('---------------------------------------------')

def empresa3():
    empresa3 = [1200,1300,8000,3000,15000]

    moda = statistics.mode(empresa3)
    print("Moda:", moda)

    media = statistics.mean(empresa3)
    print('Média:', media)

    varianca = statistics.variance(empresa3)
    print('Variança:', varianca)

    desvio_padrao = statistics.stdev(empresa3)
    print("Desvio de padrão:", desvio_padrao)

empresa3()

import statistics
# parametros

# def calcular(n1, n2):
#     print(n1 + n2)
#     print(n1 * n2)
#     print(n1 - n2)
#     print(n1 / n2)

# variaveis globais

n1 = 0
n2 = 0
def calcular2(n1, n2):
    print(n1 + n2)
    print(n1 * n2)
    print(n1 - n2)
    print(n1 / n2)

calcular2(10,2)


def calcular3():
    lista = []
    n = calcular2
    lista.append(n)
    lista.append(n2)
    print(lista)

calcular3()