# -*- coding: utf-8 -*-
"""Aula07

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SyIh3S6yAuNKCYHtNFh875YbNDEKQij3
"""

import random

# Posso criar um modulo
# Posso usar algo que está pronto no Python
#Existe um módulo chamado Random == aleatório

aleatorio = random.random()
aleatorio2 = random.random()
print(aleatorio, aleatorio2)


aleatorio3 = random.randint(1,10)
print(aleatorio3)


aleatorio4 = random.randrange(4,20)
print(aleatorio4)

import random

for n in range(1,4):
    meu_numero = int(input('>>'))
    numero_aleatorio = random.randint(1,5)


    if meu_numero == numero_aleatorio:
        print('Você ganhou!', numero_aleatorio)
        break
    else:
        print('Você errou feio! O numero é: ', numero_aleatorio)
        print('Você gastou ', n, 'chances')
        if n == 3:
          print('Você esgoutou a quantidade de chances')

disciplinas = int(input('Digite o número de diciplina: '))
soma = 0

for n in range(0, disciplinas):
   nota = float(input('>> '))

   soma = soma + nota
print('A sua média é:',soma/len(range(0, disciplinas)))

# Vamos entender alguma convenções:

# **SNAKE_CASE**

# se eu tiver um nome composto
nomeclatura_das_variaveis = 'nome_segndo_nome'


# **ESPAÇAMENTO**

# padrâo 4 espaços
# o sistema funciona com 2 espaços

if 10 > 2:
    print('é maior')
else:
    print('é menor')