# -*- coding: utf-8 -*-
"""aula 13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5-kcK3sUv2TUnVHFf868rzdOs9J5wj3
"""

# 1 - CRIE UMA FUNÇÃO PARA COMPARAR 2 NÚMEROS, QUAL É DIVISIVEL POR 3. UTILIZE VARIÁVEIS LOCAIS.

def comparar():
    n1 = int(input('>>'))
    n2 = int(input('>>'))
    igual = n1 == n2
    if n1 % 3 ==0:
      print('É divisivel', n1)
    elif n2 % 3 ==0:
      print('É divisivel', n2)
    else:
      print('Não se aplica')


comparar()

# 2 - CRIE UMA FUNÇÃO PARA MULTIPLICAR 3 NUMEROS. UTILIZAR VARIAVEIS LOCAIS.

def multiplicacao():
    n1 = 8
    n2 = 6
    n3 = 14
    multi = n1 * n2 * n3
    print('Resultado:', multi)

multiplicacao()

# 3 - CRIE UMA FUNÇÃO PARA DESCOBRIR O VALOR ELEVADO DE UM NÚMERO. GLOBAIS

n1 = int(input('Digite um número: '))

def elevado():
    quadrado = n1 ** 2
    print(quadrado)

elevado()

# 4 - CRIE UMA FUNÇÃO PARA MOSTRAR UMA MENSAGEM PERSONALIZADA NA TELA, SE O USUÁRIO PARA DIGITAR, 18 ANOS, PARAMETROS

idade = int(input('Digite sua idade: '))

if idade >= 18:
    print('Você é maior de idade!')
else:
    print('Você é menor de idade!')

# 5 - DESENVOLVA UMA FUNÇÃO PARA DESCOBRIR A IDADE DE UMA PESSOA.UTILIZE PARAMETROS

def idade(ano_atual, data_nasc):
    calc = ano_atual - ano_nasc
    print(calc)
ano_nasc = int(input('>> '))

idade(2024, ano_nasc)

# 6 - DESENVOLVA UM AFUNÇÃO PARA VER SE O BRASIL GANHOU A COPA DE 1999 UTILIZAR VARIÁVEIS LOCAIS6

def copa():
    quiz = int(input('Digite o ano: '))
    copas = [1958, 1962, 1970, 1994, 2002]
    if quiz in copas:
        print('O Brasil ganhou esse ano de', quiz,'!')
    else:
      print('Esse ano o Brasil não ganhou!')

copa()

# 7 - DESENVOLVA UM SISTEMA DE RESTAURANTE, ONDE O CLIENTE TEM OPÇÃO DE ESCOLHER ENTRE SALADA, MACARRONADA, SANDUICHE, SORVETE.  PARAMETROS.

def restaurante():
    print('Olá seja bem vindo ao restaurante Josemar!')
    print('''

    Confira o cardapio:
    1 - Salada
    2 - Macarronada
    3 - Sanduiche
    4 - Sorvete

    ''')

def escolha1():
    escolha = int(input('Digite a sua escolha: '))

    if escolha == 1:
        print('Certo você escolheu Salada, em 5 minutos seu pedido ficará pronto!')
    elif escolha == 2:
        print('Certo você escolheu Macarronada, em 5 minutos seu pedido ficará pronto!')
    elif escolha == 3:
        print('Certo você escolheu Sanduiche, em 5 minutos seu pedido ficará pronto!')
    elif escolha == 4:
        print('Certo você escolheu Sorvete, em 5 minutos seu pedido ficará pronto!')
    else:
        print('Prato não econtrado tente novamente!')
        escolha1()

restaurante()
escolha1()