# -*- coding: utf-8 -*-
"""aula08

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qYbbv9QBn_6F9YJHBX1-33KYxy4zEYb0
"""

n1 = int(input('Digite um número: '))
n2 = int(input('Digite um número: '))

if int(n1) % int(n2) == 1:
    print('Não é divisivel')
elif int(n1) % int(n2) == 0:
    print('É divisivel, e o resultado de,', n1, '%', n2)
else:
    print('Não processado')


# n1 = int(input('Digite um número: '))
# n2 = int(input('Digite um número: '))

# if n1 % n2 == 1:
#     print('Não é divisivel')
# elif n1 % n2 == 0:
#     print('A divisão de %d e %d' % (n1,n2))
# else:
#     print('Não processado')

# 1 - Escreva um programa que peça ao usuário para inserir dois números e verifique se o primeiro número é divisível pelo segundo usando o operador de módulo.

n1 = int(input('Digite um número: '))
n2 = int(input('Digite o número divisor: '))

resultado = n1 / n2

if n1 % n2 == 0:
    print(f'É divisível, o resultado é: {resultado}')
elif n1 % n2 == 1:
    print('Não é divisivel')
else:
    print('NÃO PROCESSADO')

# 2 - Peça ao usuario digitar o ano que ele deseja verificar e verifique se o determinado ano é bissexto ou não usando o operador de módulo.

ano = int(input('Digite o ano em que nasceu: '))

if ano % 100!=0 and ano % 4 == 0  or ano % 400 == 0:
    print('Ano bissexto')
else:
    print('Não é um ano bissexto')

# 3 - Escreva um programa para multiplicar por 3,  os número pares de uma lista

n = [2,4,6,8,10,12,14,16,18,20]

for i in n:
    print(i * 2)

# lista = [1,6,6,6,6]

# tupla = (10,5,6,154,'a','b','c')

# lista = [10,3,6,89,89,89]
# valor = int(input('Digite o valor da lista: '))
# n = lista.count(10)

# print('O valor: tem',n, 'indices')

# for i in lista:
#     print(i)


tupla = (10,20,30)
x, y, z = tupla

print(x, y, z)

# 1 -  Crie uma tupla chamada frutas com pelo menos 5 frutas diferentes. Em seguida, acesse e imprima o terceiro elemento da tupla.

tupla = ('Maçã','Banana','Abacaxi','Morango','Uva')

print(tupla[2])

# 2 - Crie uma tupla chamada `numeros` com alguns números inteiros. Em seguida, converta essa tupla em uma lista e imprima a lista resultante.

numeros = (2,3,8,10,4,55,154,200,330)
l = list(numeros)

print(l)

# 3 - Crie uma tupla chamada `meses` com os nomes dos meses do ano até Agosto. Use um loop `for` para imprimir cada mês em uma linha separada.

meses = ('Janeiro', 'Fevereiro', 'Março', 'Abriu','Maio', 'Junho', 'Julho', 'Agosto')


for i in meses:
    print(i)

# 4 - Crie uma lista chamada notas com algumas notas de alunos. Em seguida, converta essa lista em uma tupla e imprima a tupla resultante. Faça a média das notas.

notas = [10,7,5,9,8,8,9,10,7]
tupla = tuple(notas)
soma = sum(notas)/9

print(tupla)
print(f'A média é: {soma}')

# 5 - Crie uma lista chamada ponto que represente as coordenadas (x, y, e z) de um ponto. Em seguida, desempacote os elementos da lista em duas variáveis separadas (x ,y e z ) e imprima os valores.

ponto = [122,358,777]
x, y, z = ponto

print(x , y, z)

contador = 1
while contador <=5:
    print('Contador', contador)
    contador = contador + 1

print('------------------------')

c2 = 10
while c2 >=1:
    print('Contador', c2)
    c2 = c2 - 1

senha_correta = 12
chances = 3

while chances > 0:
    senha = input("Digite a senha ->")
if senha == senha_correta:
    print("Acesso liberado")
else:
    chances -=1
    print("Tente novamente")

if chances == 0:
   print("Chances esgotadas")

#TABUADA

c = 0
numero = int(input('>>>'))
while c <= 10:
    resultado = c * numero
    print(c, 'x', numero, '=',resultado)
    c += 1

# 1 - Contagem regressiva simples Escreva um programa que exiba uma contagem regressiva de 10 a 1, e depois imprima "Fogo!".

c = 10

while c >=0:
    print(c)
    c = c - 1

print('Fogo!')

# 2 - **Soma de números pares** Peça ao usuário que insira um número inteiro positivo e, em seguida, calcule a soma de todos os números pares de 2 até o número inserido.

c = 0
numero = int(input('Digite um numero inteiro positivo: '))

while c <= numero:
    resultado = c + numero
    print(c, '+', numero, '=', resultado)
    c += 2

# 3 - **Tabuada de multiplicação** Peça ao usuário para inserir um número inteiro e mostre a tabuada de multiplicação desse número de 1 a 10.

numero = int(input('Digite um número: '))
c = 0

while c <= 10:
    resultado = c * numero
    print(c, 'x', numero, '=', resultado)
    c += 1

# 4 - **Números ímpares reversos** Exiba uma contagem regressiva de números ímpares de 99 a 1.

c = 99

while c >=1:
    print(c)
    c -= 2

import random

aleatorio = random.randint(1,21)
aleatorio2 = random.random()

print(aleatorio)
print(aleatorio2)

import random




while True:
      print('Banco x')
      saldo = 100
      escolha  =  random.randint(1,4)
      print(f'''
        1 - Saque
        2 - Deposito
        3 - Visualizar
        4 - sair
        ''')

      if escolha == 1:
        print('faça seu saque: ')
        print(f'Seu saldo é r${saldo}')
        saque =  int(input('Digite o saque >>'))
        if saque > saldo:
             print('saldo insuficiente')
             saque =  int(input('Digite o saque >>'))
        else:
            result = saldo - saque
            print(f'Você sacou R${saque}, saldo em conta R${result}')
      elif escolha  == 2:
            print('faça seu deposito: ')
            print(f'Seu saldo é R${saldo}')
            deposito =  int(input('Digite o deposito >>'))
            result = saldo + deposito
            print(f'Você depositou R${deposito}, saldo em conta R${result}')
      elif escolha == 3:
            print(f'Seu saldo é R${saldo}')
      else:
            print('Obrigada por utilzar')

# 1 - Crie um número aleatório de 10, 5

import random

ale = random.randint(5,10)

print(ale)

# 2 - Crie 3 números aleatórios

import random

ale1 = random.randint(5,7)
ale2 = random.randint(7,14)
ale3 = random.randint(10,21)

print(ale1, ale2, ale3)

# 3 - Crie um número aleatório entre 10 a 30 utilize o range()

import random

ale = random.randrange(10,30)

print(ale)