# -*- coding: utf-8 -*-
"""aula09

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uNQLN0JTd9KfTyD-pvCc1dr8bsa45nN6
"""

# aula passada vimos loops, for, while.

# nessa aula vamos ver funções em python
# semântico** levar o nome daquilo que fezem


def display():
    name = input('Digite seu nome: ')
    print(f'Seja bem vindo(a), {name}')
    for n in range(1, 4):
        if name:
            print('Temos algumas opções de pratos')
        else:
            print('O restaurante está fechado')
    n = 3
    while n > 0:
        print(name)
        n = n -1

display()

def menu():
    print('''
Bem vindo(a) ao restaurante R
Opções de pratos:

Digite um nº a sua escolha:

1 - Macarrão
2 - Sopa
3 - Carne Assada

''')

def plate():
    numero1 = 'Macarrão'
    numero2 = 'Sopa'
    numero3 = 'Carne Asssada'
    name = input('Digite seu nome: ')
    escolha = int(input('Digite sua escolha: '))
    if escolha == 1:
        print(f'{name}, você escolheu {numero1}')
    elif escolha == 2:
        print(f'{name}, você escolheu {numero2}')
    elif escolha == 3:
        print(f'{name}, você escolheu {numero3}')
    else:
        print('Essa opção não existe!')

def drink():
    print('''
Poxa, lega agora escolha sua bebida:

1 - Água
2 - Refrigerante
3 - Cerveja

''')

    numero1 = 'Água'
    numero2 = 'Refrigerante'
    numero3 = 'Cerveja'
    escolha = int(input('Digite sua escolha: '))
    if escolha == 1:
        print(f'Você escolheu {numero1}')
    elif escolha == 2:
        print(f'Você escolheu {numero2}')
    elif escolha == 3:
        print(f'Você escolheu {numero3}')
    else:
        print('Essa opção não existe!')


def farewell():
    print('Aguarde na mesa, seu pedido ficará pronto em 5 minutos, Obrigado!')

def restaurante():
    menu()
    plate()
    drink()
    farewell()


restaurante()

# Parametros

def display(name):
    print('Olá seja bem vindo(a)', name)


def soma(n1, n2):
    print('resultado: ',n1+n2)


display('José')
soma(10,1)

# VOCÊ É O DESENVOLVEDOR DO BANCO X, E PRECISA CRIAR OS SISTEMAS DOS CAIXAS:

# CRIE UM SISTEMA DE BANCO COM FUNÇÕES
# ESSE SISTEMA PRECISA TER SAQUE, DEPOSITO, VISUALIZAÇÃO.
# E TAMBÉM A POSSIBILIDADE DE PODE SAIR E MUDAR A OPERAÇÃO


import random

print('Bem vindo ao Banco R!')

def saque(saldo, valor_saque):
    result = saldo - valor_saque
    print(f'SALDO R${result}')

def deposito(saldo, valor_deposito):
    result = saldo + valor_deposito
    print(f'SALDO R${result}')

def visual(saldo):
    print(f'SALDO R${saldo}')

def parar(escolha):
    escolha != '1'or '2' or '3'
    print('Escolha incorreta, tente novamente!')

def banco():
    saldo_randomico = random.randint(100,10000)
    print('''
    Olá escolha a operação desejada

    1 - Saldo
    2 - Deposito
    3 - Saque
''')
    escolha_operacao = int(input('Digite sua escolha: '))
    if escolha_operacao == 1:
        visual(saldo_randomico)
    elif escolha_operacao == 2:
        print(f'Seu saldo é {saldo_randomico},00')
        dep = int(input('Digite o valor que deseja depositar: '))
        deposito(saldo_randomico,dep)
    elif escolha_operacao == 3:
        print(f'Seu saldo é {saldo_randomico},00')
        saq = int(input('Digite o valor que deseja sacar: '))
        saque(saldo_randomico,saq)
    else:
        parar(escolha_operacao)
        banco()

while True:
    banco()

quadrado = lambda x: x ** 2
print(quadrado(5))

# 1 - Crie uma função lambda que retorne o dobro de um número.

lam = lambda x: x ** 2
print(lam(4))

# 2 - Crie uma função lambda que calcule a soma de dois números.

calc = lambda x, y: x + y
print(calc(4,16))

# 3 - Crie uma função lambda que verifique se um número é par.

num = lambda x: x %2 == 0
print(num(8))

# 4 - Crie uma função lambda que converta uma string em maiúsculas.

fun = lambda palavra: palavra.upper()
print(fun('frase'))

# 5 - Crie uma função lambda que calcule o produto de três números.

calc = lambda x, y, z: x + y + z
print(calc(20,8,12))

# Crie um banco com funções lambda()

print('Bem vindo ao banco Josemar!')

saldo = 1000

print('''
Escolha a operação

1 - Saldo
2 - Deposita
3 - Saque

''')

conta = int(input('Digite a sua escolha: '))

if conta == 1:
  print(f'Seu saldo é R${saldo},00')
elif conta == 2:
    print(f'Seu saldo é R${saldo},00')
    dep = int(input('Digite o valor que deseja depositar: '))
    deposito = lambda x: x
    print(deposito(dep)+saldo)
elif conta == 3:
    print(f'Seu saldo é R${saldo},00')
    saq = int(input('Digite o valor que deseja sacar: '))
    saque = lambda y, x: y - x
    print(saque(saldo,saq))
else:
    print('Error tente novamente!')